### PR TITLE
web-based attachment viewing

### PR DESCRIPTION
**Pull request by randomairborne**
This still requires a Discord web proxy, and will not function until a specific environment variable is set.

### CODE REVIEW

**Comment by Scotsguy** [comment]
I'm not a fan of, as I presume the endgoal of this PR is, downloading users' attachments and hosting them somewhere else, both for privacy concerns (this probably* makes us a data controller under GDPR) and complexity of deployment (now we need a database). Is this just to make it easier to view attachments?
*not your lawyer

**Comment by randomairborne** [comment]
if implemented as #5 does it- and there are other ways- it never stores user data, nor does it need a database, only proxying the Discord CDN. I made a very similar bot for another server and they had the same concerns.  It's mostly a usability thing so people who help don't have to download log files when people send them as attachments. It doesn't need a database, the added complexity amounts at most to a single additional docker container which requires almost no configuration.  It could even be an Nginx rule with an HTML file and a proxy_pass rule.

**Comment by randomairborne** [comment]
I made a gist with the needed files for Nginx proxying: https://gist.github.com/randomairborne/92852dafb84f742c8f7bff1474a2a2c5

**Comment by randomairborne** [comment]
Is this wanted? Or shall i close the PR?

**Comment by randomairborne** [comment]
Closing this, as it appears to not be a planned feature.

**Pull request closed without merging**
